[package]
name = "shared-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0.100"
walkdir = "2"
bincode = "1"
zstd = "0.13"
